version: "3.8"

volumes:
  jenkins-data:
    name: jenkins-data

networks:
  minikube:
    external: true

services:
  jenkins:
    container_name: jenkins
    image: jenkins-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    hostname: jenkins-docker
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - minikube
    ports:
      - 127.0.0.1:8090:8080
    expose:
      - 50000
